function [BSGridCFD_2D, BSGridCFD_3D] = GRE_EbFVM(BSModels, BSGridCFD_2D, BSGridCFD_3D)
% *************************************************************************************************************************************************************
% Evalute the instantaneous hydrodynamic problem of a bearing simulation
% Solve the (p-theta) Generalised Reynolds Equation using the EbFVM
% Calculate the hydrodynamic pressure (pHydro) and lubricant film fraction (thetaHydro)
% *************************************************************************************************************************************************************

%% Initial hydrodynamic fields
    pHydro                        = zeros(1, BSGridCFD_2D.nodes.numNodes);
    pHydro(isnan(pHydro))         = 0;    
    thetaHydro                    = zeros(1, BSGridCFD_2D.nodes.numNodes);
    thetaHydro(isnan(thetaHydro)) = 1;    
    
%% Update lubricant transport properties
    BSGridCFD_2D.nodes = GRE_lubricantTransport(BSModels, BSGridCFD_2D.nodes);

%% Update hydrodynamic coefficient matrices
    [BSGridCFD_2D] = Organise_JFO_EbFVM_cfdCoeffs(BSModels, BSGridCFD_2D);

%% Solve instantaneous hydrodynamic problem (solve linear system) (Convert routine to a MEX function to improve computational efficiency)
    % [pHydro, thetaHydro] = sorSolver_FVMbE_JFO_mex(pHydro, thetaHydro, ...
    %                                   BSGridCFD_2D.calcMatrices.cfdCoeffs.JA, ...
    %                                   BSGridCFD_2D.calcMatrices.cfdCoeffs.Ap_BC, ...
    %                                   BSGridCFD_2D.calcMatrices.cfdCoeffs.Atheta_BC, ...
    %                                   BSGridCFD_2D.calcMatrices.cfdCoeffs.B_BC, ...
    %                                   BSModels.modelPressure.cavitationPressure / BSModels.modelBearing.dimensionless.df_p_GRE, ...
    %                                   BSModels.numericalOptions.solverLinear.relaxationFactor, ...
    %                                   1.0, ...
    %                                   BSModels.numericalOptions.solverLinear.maximumIterations, ...
    %                                   BSModels.numericalOptions.solverLinear.toleranceError);

        [pHydro, thetaHydro] = sorSolver_FVMbE_JFO(pHydro, thetaHydro, ...
                                      BSGridCFD_2D.calcMatrices.cfdCoeffs.JA, ...
                                      BSGridCFD_2D.calcMatrices.cfdCoeffs.Ap_BC, ...
                                      BSGridCFD_2D.calcMatrices.cfdCoeffs.Atheta_BC, ...
                                      BSGridCFD_2D.calcMatrices.cfdCoeffs.B_BC, ...
                                      BSModels.modelPressure.cavitationPressure / BSModels.modelBearing.dimensionless.df_p_GRE, ...
                                      BSModels.numericalOptions.solverLinear.relaxationFactor, ...
                                      1.0, ...
                                      BSModels.numericalOptions.solverLinear.maximumIterations, ...
                                      BSModels.numericalOptions.solverLinear.toleranceError);

%% Update hydrodynamic fields
    BSGridCFD_2D.nodes.pHydro     = pHydro'.* BSModels.modelBearing.dimensionless.df_p_GRE ./ BSModels.modelBearing.dimensionless.df_p;
    BSGridCFD_2D.nodes.thetaHydro = thetaHydro';

end % *** END FUNCTION % **************************************************************************************************************************************
